"""FCSUti CPI-U Composite Index for SPM threshold inflation adjustment.

The FCSUti composite re-weights five CPI-U component series (food, apparel,
shelter, utilities, and telephone) in proportion to the FCSUti expenditure
shares of consumer units with children.
It replaces the All-Items CPI-U used in the pre-2021 SPM methodology.

BLS re-derives the component weights from the CE expenditure sample used
for the target-year threshold itself, so the weights roll with the 5-year
lagged window. This module supports three ways of supplying weights:

1. Pass a ``weights`` dict explicitly (highest precedence).
2. Compute weights from a CE FMLI DataFrame with
   :func:`compute_fcsuti_weights_from_ce`.
3. Fall back to :data:`FCSUTI_WEIGHTS`, a static approximation. A
   :class:`RuntimeWarning` is emitted in this case so runs using the
   fallback are visible in logs.

References
----------
- Garner, T. (2021). *Alternative Measures of the Extent and Severity
  of Poverty: A Review and Data Users' Guide to the Supplemental
  Poverty Measure.* BLS, https://www.bls.gov/pir/spm/garner_spm_choices_03_15_21.pdf
- BLS SPM Thresholds: https://www.bls.gov/pir/spm/spm_thresholds_2024.htm
"""

import json
import os
import warnings
from functools import lru_cache
from importlib import resources
from typing import Mapping, Optional

import numpy as np
import pandas as pd


@lru_cache(maxsize=1)
def _packaged_cpi_store() -> dict:
    """Load the packaged CPI annual-average store.

    Generated by ``scripts/build_cpi_store.py`` from the BLS public
    data API with FRED cross-validation — never hand-edited. Serves as
    the offline path when the BLS API is unreachable or over quota.
    """
    ref = resources.files("spm_calculator").joinpath(
        "data/bls/cpi_annual.json"
    )
    return json.loads(ref.read_text())


def get_packaged_cpi_series(
    series_id: str,
    start_year: int,
    end_year: int,
) -> pd.Series:
    """Annual averages for a CPI series from the packaged store."""
    store = _packaged_cpi_store()["series"]
    if series_id not in store:
        raise KeyError(
            f"{series_id} is not in the packaged CPI store ({sorted(store)})"
        )
    series = pd.Series(
        {int(y): v for y, v in store[series_id].items()},
        name=series_id,
    ).sort_index()
    return series[(series.index >= start_year) & (series.index <= end_year)]


# BLS CPI series IDs for FCSUti components.
# Source: https://www.bls.gov/cpi/data.htm
CPI_SERIES = {
    "food": "CUUR0000SAF",  # Food
    "food_at_home": "CUUR0000SAF11",  # Food at home
    "food_away": "CUUR0000SEFV",  # Food away from home
    "apparel": "CUUR0000SAA",  # Apparel
    "shelter": "CUUR0000SAH1",  # Shelter
    "utilities": "CUUR0000SAH2",  # Fuels and utilities
    "telephone": "CUUR0000SEED",  # Telephone services
    "all_items": "CUUR0000SA0",  # All items (reference only)
}

# TODO(2026 method): decide whether and how to add home internet using
# CUUR0000SEEE03 (Internet services and electronic information providers).
# CUUR0000SEEE is the broader Information technology, hardware and services
# series, so it must not be used as a home-internet proxy.

# Static fallback FCSUti expenditure shares for consumer units with
# children. These are a rough approximation of CE shares; BLS re-derives
# them annually from the 5-year CE sample used for each threshold year.
# Prefer supplying ``weights=`` explicitly or deriving via
# :func:`compute_fcsuti_weights_from_ce`.
FCSUTI_WEIGHTS: dict[str, float] = {
    # The five valid legacy weights are normalized over their 0.96 total
    # after removing the erroneous 0.04 SEEE-as-internet allocation.
    "food": 0.30 / 0.96,
    "apparel": 0.05 / 0.96,
    "shelter": 0.45 / 0.96,
    "utilities": 0.12 / 0.96,
    "telephone": 0.04 / 0.96,
}

# FMLI expenditure-column pairs (PQ = previous quarter, CQ = current
# quarter) for each directly-summable FCSUti component. Utilities and
# telephone are handled specially in
# :func:`compute_fcsuti_weights_from_ce` because the FMLI ``UTIL``
# summary already contains ``TELEPH`` (UTIL = NTLGAS + ELCTRC + ALLFUL
# + TELEPH + WATRPS): the utilities weight uses UTIL minus TELEPH so
# telephone is not double-counted. Home internet has no FMLI summary
# variable; CE-derived and static weights omit it pending the 2026-method
# decision documented beside :data:`CPI_SERIES`.
_FMLI_EXPENDITURE_COLUMNS: dict[str, tuple[str, str]] = {
    "food": ("FOODPQ", "FOODCQ"),
    "apparel": ("APPARPQ", "APPARCQ"),
    "shelter": ("SHELTPQ", "SHELTCQ"),
    "utilities": ("UTILPQ", "UTILCQ"),
    "telephone": ("TELEPHPQ", "TELEPHCQ"),
}

# Owner mortgage-principal outlay columns (owned home + owned vacation
# home); added to the shelter weight to match the SPM outlays concept.
_MORTGAGE_PRINCIPAL_COLUMNS: tuple[tuple[str, str], ...] = (
    ("EMRTPNOP", "EMRTPNOC"),
    ("MRTPRNOP", "MRTPRNOC"),
)


def fetch_bls_cpi_series(
    series_id: str,
    start_year: int = 2010,
    end_year: int = 2024,
    registration_key: Optional[str] = None,
) -> pd.Series:
    """Fetch an annual-average CPI series from the BLS public API.

    Args:
        series_id: BLS series ID (e.g. ``"CUUR0000SA0"``).
        start_year: Inclusive start year.
        end_year: Inclusive end year.
        registration_key: Optional BLS v2 registration key. Defaults to
            ``$BLS_API_KEY`` if set. Without a key, BLS rate-limits
            unauthenticated requests to 25 queries per IP per day —
            enough to break `get_fcsuti_cpi` (six component series) after
            four calls.

    Returns:
        Series of annual-average CPI values indexed by calendar year.
    """
    import requests

    # BLS Public Data API v2. Registered access is documented at
    # https://www.bls.gov/developers/; registered callers get 500
    # queries/day per key with twenty-year history and annual averages.
    #
    # The API caps each request's span (10 years unregistered, 20
    # registered) and silently returns only the FIRST years of an
    # over-long span rather than erroring — a 2005-2025 unregistered
    # request comes back as 2005-2014. Chunk long spans so callers get
    # the range they asked for.
    url = "https://api.bls.gov/publicAPI/v2/timeseries/data/"
    key = registration_key or os.environ.get("BLS_API_KEY")
    max_span = 20 if key else 10

    values: dict[int, float] = {}
    chunk_start = start_year
    while chunk_start <= end_year:
        chunk_end = min(chunk_start + max_span - 1, end_year)
        payload = {
            "seriesid": [series_id],
            "startyear": str(chunk_start),
            "endyear": str(chunk_end),
            "annualaverage": True,
        }
        if key:
            payload["registrationkey"] = key

        response = requests.post(url, json=payload, timeout=30)
        response.raise_for_status()
        data = response.json()
        if data["status"] != "REQUEST_SUCCEEDED":
            raise ValueError(
                f"BLS API error: {data.get('message', 'Unknown error')}"
            )

        series_data = data["Results"]["series"][0]["data"]
        # Filter to annual averages (period code M13).
        for d in series_data:
            if d["period"] == "M13":
                values[int(d["year"])] = float(d["value"])
        chunk_start = chunk_end + 1

    return pd.Series(values, name=series_id).sort_index()


def compute_fcsuti_weights_from_ce(
    ce_df: pd.DataFrame,
    weight_col: str = "FINLWT21",
    children_col: str = "PERSLT18",
    include_mortgage_principal: bool = True,
) -> dict[str, float]:
    """Derive FCSUti expenditure shares from a CE FMLI DataFrame.

    For each FCSUti component, computes the survey-weighted total
    expenditure across consumer units with at least one child, then
    normalizes so the returned shares sum to 1.0. Matches the BLS
    Garner (2021) methodology where the composite weights are derived
    from the same CE sample used to compute the threshold itself.

    Component construction (see :data:`_FMLI_EXPENDITURE_COLUMNS`):
    the utilities share is ``UTIL - TELEPH`` because the FMLI ``UTIL``
    summary already contains telephone; the telephone share is
    ``TELEPH``; shelter adds owner mortgage-principal outlays (SPM
    outlays concept) when ``include_mortgage_principal`` is set.

    Args:
        ce_df: CE FMLI DataFrame (one row per CU-interview).
        weight_col: Column with the CU's calibrated survey weight.
            Defaults to ``FINLWT21`` (standard FMLI name).
        children_col: Column with the number of persons under 18 in
            the CU. Defaults to ``PERSLT18``.
        include_mortgage_principal: When True (default), add owner
            mortgage-principal outlays to the shelter share.

    Returns:
        Dict mapping each FCSUti component present in ``ce_df`` to a
        share in ``[0, 1]``. Shares sum to 1.0. Components without
        their expenditure columns in the data are omitted.

    Raises:
        ValueError: If ``ce_df`` is missing ``weight_col`` or
            ``children_col``, or if no CUs have children, or if no
            FCSUti component columns are present, or if a survey weight
            is nonnumeric, nonfinite, or not strictly positive.
    """
    if weight_col not in ce_df.columns:
        raise ValueError(
            f"CE DataFrame is missing weight column '{weight_col}'"
        )
    if children_col not in ce_df.columns:
        raise ValueError(
            f"CE DataFrame is missing children column '{children_col}'"
        )

    with_children = ce_df[ce_df[children_col] > 0]
    if len(with_children) == 0:
        raise ValueError("No consumer units with children in CE DataFrame")

    try:
        weights = pd.to_numeric(
            with_children[weight_col], errors="raise"
        ).to_numpy(dtype=float)
    except (TypeError, ValueError) as error:
        raise ValueError(
            f"CE survey weights in '{weight_col}' must be numeric"
        ) from error
    if not (np.isfinite(weights) & (weights > 0)).all():
        raise ValueError(
            f"CE survey weights in '{weight_col}' must be finite and "
            "strictly positive"
        )

    def _weighted_expenditure(pq: str, cq: str) -> Optional[float]:
        present = {
            pq: pq in with_children.columns,
            cq: cq in with_children.columns,
        }
        if not any(present.values()):
            return None
        if not all(present.values()):
            missing = [
                column for column, exists in present.items() if not exists
            ]
            raise ValueError(
                f"CE data is missing expenditure pair member(s) {missing} "
                f"from {pq}/{cq}"
            )
        values = (
            with_children[pq].fillna(0).to_numpy()
            + with_children[cq].fillna(0).to_numpy()
        )
        return float(np.sum(values * weights))

    totals: dict[str, float] = {}
    for component, (pq, cq) in _FMLI_EXPENDITURE_COLUMNS.items():
        if component == "food":
            # Row-wise construction robust to the April 2023 CE food
            # redesign (GROCER-based vintages mixed with legacy FOOD
            # vintages in pooled windows). Lazy import avoids a
            # circular import at module load.
            from .ce_threshold import _food_expenditure

            food_values = _food_expenditure(with_children).to_numpy()
            exp = float(np.sum(food_values * weights))
            if exp > 0:
                totals[component] = exp
            continue
        exp = _weighted_expenditure(pq, cq)
        if exp is None:
            continue
        totals[component] = exp

    # UTIL contains TELEPH; carve telephone out of utilities so the
    # composite weights don't double-count it.
    if "utilities" in totals and "telephone" in totals:
        totals["utilities"] = max(
            totals["utilities"] - totals["telephone"], 0.0
        )

    if include_mortgage_principal and "shelter" in totals:
        for pq, cq in _MORTGAGE_PRINCIPAL_COLUMNS:
            principal = _weighted_expenditure(pq, cq)
            if principal is not None:
                totals["shelter"] += principal

    if not totals:
        raise ValueError(
            "CE DataFrame has no FCSUti expenditure columns "
            f"({list(_FMLI_EXPENDITURE_COLUMNS)})"
        )

    total = sum(totals.values())
    if total <= 0:
        raise ValueError("Total FCSUti expenditure is zero or negative")

    return {component: value / total for component, value in totals.items()}


_STATIC_WEIGHTS_WARNING = (
    "Using static FCSUti weights approximation. For BLS-fidelity "
    "inflation adjustment, derive weights from the CE sample via "
    "compute_fcsuti_weights_from_ce() or supply an explicit "
    "weights= dict keyed by component name."
)


def _resolve_weights(
    weights: Optional[Mapping[str, float]],
) -> dict[str, float]:
    """Validate a supplied ``weights`` mapping (never warns).

    The fallback-use RuntimeWarning is emitted by the public
    entry-point functions (``get_fcsuti_cpi``,
    ``get_fcsuti_inflation_factor``) so that ``stacklevel=2`` attributes
    the warning to the user regardless of which entry point is called.
    """
    if weights is None:
        return dict(FCSUTI_WEIGHTS)
    if not weights:
        raise ValueError("weights mapping is empty")
    try:
        resolved = {
            component: float(weight) for component, weight in weights.items()
        }
    except (TypeError, ValueError) as error:
        raise ValueError("FCSUti weights must be numeric") from error
    values = np.asarray(list(resolved.values()), dtype=float)
    if not (np.isfinite(values) & (values > 0)).all():
        raise ValueError("FCSUti weights must be finite and strictly positive")
    return resolved


@lru_cache(maxsize=8)
def _cached_fcsuti_cpi(
    start_year: int,
    end_year: int,
    base_year: int,
    weights_items: tuple[tuple[str, float], ...],
) -> pd.Series:
    """Immutable-inputs worker for :func:`get_fcsuti_cpi`."""
    if start_year > end_year:
        raise ValueError("start_year must be less than or equal to end_year")
    if not start_year <= base_year <= end_year:
        raise ValueError(
            f"base_year {base_year} must fall within the requested "
            f"{start_year}-{end_year} range"
        )

    weights = dict(weights_items)
    components: dict[str, pd.Series] = {}
    for component in weights:
        series_id = CPI_SERIES.get(component)
        if series_id is None:
            raise ValueError(
                f"No CPI series is configured for FCSUti component "
                f"'{component}'"
            )
        try:
            components[component] = fetch_bls_cpi_series(
                series_id, start_year, end_year
            )
        except Exception as e:
            try:
                components[component] = get_packaged_cpi_series(
                    series_id, start_year, end_year
                )
                warnings.warn(
                    f"BLS API unavailable for {component} ({e}); "
                    "using the packaged CPI store.",
                    RuntimeWarning,
                    stacklevel=2,
                )
            except KeyError as store_error:
                raise ValueError(
                    f"Could not load required {component} CPI series "
                    f"{series_id} from either the BLS API or packaged store"
                ) from store_error

    required_years = pd.Index(range(start_year, end_year + 1))
    missing_by_component = {
        component: [
            int(year)
            for year in required_years
            if year not in series.index or pd.isna(series.get(year))
        ]
        for component, series in components.items()
    }
    missing_by_component = {
        component: years
        for component, years in missing_by_component.items()
        if years
    }
    if missing_by_component:
        raise ValueError(
            "FCSUti CPI component series are missing required annual values: "
            f"{missing_by_component}"
        )

    df = pd.DataFrame(
        {
            component: series.reindex(required_years).astype(float)
            for component, series in components.items()
        },
        index=required_years,
    )

    # Each CPI series carries its own reference base, so raw levels are
    # not commensurate: summing them weights each component by its
    # level as well as its share (with 2024 levels, shelter's effective
    # weight was 55 percent against a stated 47, telephone's 1.2
    # against 4 — caught by cross-model review 2026-07-18). Rebase
    # every component to the composite's base year before weighting so
    # the stated expenditure shares are the effective ones.
    denom = sum(weights.values())
    renormalized = {c: w / denom for c, w in weights.items()}

    fcsuti = pd.Series(0.0, index=df.index)
    for component, weight in renormalized.items():
        rebased = df[component] / df[component][base_year] * 100
        fcsuti += rebased * weight

    fcsuti = fcsuti / fcsuti[base_year] * 100
    if not np.isfinite(fcsuti.to_numpy()).all():
        raise ValueError("FCSUti CPI composite contains nonfinite values")
    fcsuti.name = "FCSUti CPI-U"
    return fcsuti


def get_fcsuti_cpi(
    start_year: int = 2010,
    end_year: int = 2024,
    base_year: int = 2024,
    weights: Optional[Mapping[str, float]] = None,
) -> pd.Series:
    """Compute the FCSUti composite CPI index.

    Args:
        start_year: Inclusive start year for the index.
        end_year: Inclusive end year for the index.
        base_year: Year normalized to 100.
        weights: Optional component-share mapping (e.g. the output of
            :func:`compute_fcsuti_weights_from_ce`). When None, falls
            back to :data:`FCSUTI_WEIGHTS` with a
            :class:`RuntimeWarning` so callers notice when the static
            approximation is in use.

    Returns:
        Annual FCSUti CPI index with base ``base_year`` = 100.

    Raises:
        ValueError: If the base year is outside the requested range or
            any required component lacks an annual value for any year
            in that range. The function never substitutes another base
            year or returns a partially defined composite.
    """
    if weights is None:
        warnings.warn(
            _STATIC_WEIGHTS_WARNING,
            RuntimeWarning,
            stacklevel=2,
        )
    resolved = _resolve_weights(weights)
    return _cached_fcsuti_cpi(
        start_year,
        end_year,
        base_year,
        tuple(sorted(resolved.items())),
    )


def get_fcsuti_inflation_factor(
    from_year: int,
    to_year: int,
    weights: Optional[Mapping[str, float]] = None,
) -> float:
    """Inflation factor between two years via the FCSUti composite.

    Component series come from the BLS API, falling back per series to
    the packaged CPI store (``data/bls/cpi_annual.json``, generated by
    ``scripts/build_cpi_store.py``). If a requested year is outside
    every available series, this raises rather than guessing — the
    previous behavior of substituting a hand-entered factor table or a
    flat 4 percent per year produced silently wrong output.

    Args:
        from_year: Starting year (sets the index base).
        to_year: Target year.
        weights: Optional FCSUti component shares. See
            :func:`get_fcsuti_cpi`.

    Returns:
        Factor to multiply ``from_year`` dollars by to get ``to_year``
        dollars.

    Raises:
        ValueError: If the composite cannot be built for both years.
    """
    if from_year == to_year:
        return 1.0

    if weights is None:
        warnings.warn(
            _STATIC_WEIGHTS_WARNING,
            RuntimeWarning,
            stacklevel=2,
        )
        weights = FCSUTI_WEIGHTS

    try:
        fcsuti = get_fcsuti_cpi(
            start_year=min(from_year, to_year),
            end_year=max(from_year, to_year),
            base_year=from_year,
            weights=weights,
        )
    except ValueError as error:
        raise ValueError(
            f"FCSUti composite unavailable for ({from_year}, "
            f"{to_year}): {error}. Regenerate the packaged CPI store "
            "(scripts/build_cpi_store.py) if the requested year has "
            "since been published."
        ) from error
    if to_year not in fcsuti.index or from_year not in fcsuti.index:
        raise ValueError(
            f"FCSUti composite unavailable for ({from_year}, "
            f"{to_year}); available years: {list(fcsuti.index)}. "
            "Regenerate the packaged CPI store "
            "(scripts/build_cpi_store.py) if the requested year has "
            "since been published."
        )
    factor = float(fcsuti[to_year] / fcsuti[from_year])
    if not np.isfinite(factor) or factor <= 0:
        raise ValueError(
            f"FCSUti inflation factor for ({from_year}, {to_year}) "
            "must be finite and positive"
        )
    return factor
