"""FCSUti CPI-U Composite Index for SPM threshold inflation adjustment.

The FCSUti composite re-weights five CPI-U component series (food, apparel,
shelter, utilities, telephone, and — for post-2018 vintages — internet) in
proportion to the FCSUti expenditure shares of consumer units with children.
It replaces the All-Items CPI-U used in the pre-2021 SPM methodology.

BLS re-derives the component weights from the CE expenditure sample used
for the target-year threshold itself, so the weights roll with the 5-year
lagged window. This module supports three ways of supplying weights:

1. Pass a ``weights`` dict explicitly (highest precedence).
2. Compute weights from a CE FMLI DataFrame with
   :func:`compute_fcsuti_weights_from_ce`.
3. Fall back to :data:`FCSUTI_WEIGHTS`, a static approximation. A
   :class:`RuntimeWarning` is emitted in this case so runs using the
   fallback are visible in logs.

References
----------
- Garner, T. (2021). *Alternative Measures of the Extent and Severity
  of Poverty: A Review and Data Users' Guide to the Supplemental
  Poverty Measure.* BLS, https://www.bls.gov/pir/spm/garner_spm_choices_03_15_21.pdf
- BLS SPM Thresholds: https://www.bls.gov/pir/spm/spm_thresholds_2024.htm
"""

import json
import os
import warnings
from functools import lru_cache
from importlib import resources
from typing import Mapping, Optional

import numpy as np
import pandas as pd


@lru_cache(maxsize=1)
def _packaged_cpi_store() -> dict:
    """Load the packaged CPI annual-average store.

    Generated by ``scripts/build_cpi_store.py`` from the BLS public
    data API with FRED cross-validation — never hand-edited. Serves as
    the offline path when the BLS API is unreachable or over quota.
    """
    ref = resources.files("spm_calculator").joinpath(
        "data/bls/cpi_annual.json"
    )
    return json.loads(ref.read_text())


def get_packaged_cpi_series(
    series_id: str,
    start_year: int,
    end_year: int,
) -> pd.Series:
    """Annual averages for a CPI series from the packaged store."""
    store = _packaged_cpi_store()["series"]
    if series_id not in store:
        raise KeyError(
            f"{series_id} is not in the packaged CPI store "
            f"({sorted(store)})"
        )
    series = pd.Series(
        {int(y): v for y, v in store[series_id].items()},
        name=series_id,
    ).sort_index()
    return series[(series.index >= start_year) & (series.index <= end_year)]


# BLS CPI series IDs for FCSUti components.
# Source: https://www.bls.gov/cpi/data.htm
CPI_SERIES = {
    "food": "CUUR0000SAF",  # Food
    "food_at_home": "CUUR0000SAF11",  # Food at home
    "food_away": "CUUR0000SEFV",  # Food away from home
    "apparel": "CUUR0000SAA",  # Apparel
    "shelter": "CUUR0000SAH1",  # Shelter
    "utilities": "CUUR0000SAH2",  # Fuels and utilities
    "telephone": "CUUR0000SEED",  # Telephone services
    "internet": "CUUR0000SEEE",  # Internet services
    "all_items": "CUUR0000SA0",  # All items (reference only)
}

# Static fallback FCSUti expenditure shares for consumer units with
# children. These are a rough approximation of CE shares; BLS re-derives
# them annually from the 5-year CE sample used for each threshold year.
# Prefer supplying ``weights=`` explicitly or deriving via
# :func:`compute_fcsuti_weights_from_ce`.
FCSUTI_WEIGHTS: dict[str, float] = {
    "food": 0.30,
    "apparel": 0.05,
    "shelter": 0.45,
    "utilities": 0.12,
    "telephone": 0.04,
    "internet": 0.04,
}

# FMLI expenditure-column pairs (PQ = previous quarter, CQ = current
# quarter) for each directly-summable FCSUti component. Utilities and
# telephone are handled specially in
# :func:`compute_fcsuti_weights_from_ce` because the FMLI ``UTIL``
# summary already contains ``TELEPH`` (UTIL = NTLGAS + ELCTRC + ALLFUL
# + TELEPH + WATRPS): the utilities weight uses UTIL minus TELEPH so
# telephone is not double-counted. Home internet has no FMLI summary
# variable; CE-derived weights omit it (the static fallback keeps a
# small internet share for the CPI composite).
_FMLI_EXPENDITURE_COLUMNS: dict[str, tuple[str, str]] = {
    "food": ("FOODPQ", "FOODCQ"),
    "apparel": ("APPARPQ", "APPARCQ"),
    "shelter": ("SHELTPQ", "SHELTCQ"),
    "utilities": ("UTILPQ", "UTILCQ"),
    "telephone": ("TELEPHPQ", "TELEPHCQ"),
}

# Owner mortgage-principal outlay columns (owned home + owned vacation
# home); added to the shelter weight to match the SPM outlays concept.
_MORTGAGE_PRINCIPAL_COLUMNS: tuple[tuple[str, str], ...] = (
    ("EMRTPNOP", "EMRTPNOC"),
    ("MRTPRNOP", "MRTPRNOC"),
)


def fetch_bls_cpi_series(
    series_id: str,
    start_year: int = 2010,
    end_year: int = 2024,
    registration_key: Optional[str] = None,
) -> pd.Series:
    """Fetch an annual-average CPI series from the BLS public API.

    Args:
        series_id: BLS series ID (e.g. ``"CUUR0000SA0"``).
        start_year: Inclusive start year.
        end_year: Inclusive end year.
        registration_key: Optional BLS v2 registration key. Defaults to
            ``$BLS_API_KEY`` if set. Without a key, BLS rate-limits
            unauthenticated requests to 25 queries per IP per day —
            enough to break `get_fcsuti_cpi` (six component series) after
            four calls.

    Returns:
        Series of annual-average CPI values indexed by calendar year.
    """
    import requests

    # BLS Public Data API v2. Registered access is documented at
    # https://www.bls.gov/developers/; registered callers get 500
    # queries/day per key with twenty-year history and annual averages.
    #
    # The API caps each request's span (10 years unregistered, 20
    # registered) and silently returns only the FIRST years of an
    # over-long span rather than erroring — a 2005-2025 unregistered
    # request comes back as 2005-2014. Chunk long spans so callers get
    # the range they asked for.
    url = "https://api.bls.gov/publicAPI/v2/timeseries/data/"
    key = registration_key or os.environ.get("BLS_API_KEY")
    max_span = 20 if key else 10

    values: dict[int, float] = {}
    chunk_start = start_year
    while chunk_start <= end_year:
        chunk_end = min(chunk_start + max_span - 1, end_year)
        payload = {
            "seriesid": [series_id],
            "startyear": str(chunk_start),
            "endyear": str(chunk_end),
            "annualaverage": True,
        }
        if key:
            payload["registrationkey"] = key

        response = requests.post(url, json=payload, timeout=30)
        response.raise_for_status()
        data = response.json()
        if data["status"] != "REQUEST_SUCCEEDED":
            raise ValueError(
                f"BLS API error: {data.get('message', 'Unknown error')}"
            )

        series_data = data["Results"]["series"][0]["data"]
        # Filter to annual averages (period code M13).
        for d in series_data:
            if d["period"] == "M13":
                values[int(d["year"])] = float(d["value"])
        chunk_start = chunk_end + 1

    return pd.Series(values, name=series_id).sort_index()


def compute_fcsuti_weights_from_ce(
    ce_df: pd.DataFrame,
    weight_col: str = "FINLWT21",
    children_col: str = "PERSLT18",
    include_mortgage_principal: bool = True,
) -> dict[str, float]:
    """Derive FCSUti expenditure shares from a CE FMLI DataFrame.

    For each FCSUti component, computes the survey-weighted total
    expenditure across consumer units with at least one child, then
    normalizes so the returned shares sum to 1.0. Matches the BLS
    Garner (2021) methodology where the composite weights are derived
    from the same CE sample used to compute the threshold itself.

    Component construction (see :data:`_FMLI_EXPENDITURE_COLUMNS`):
    the utilities share is ``UTIL - TELEPH`` because the FMLI ``UTIL``
    summary already contains telephone; the telephone share is
    ``TELEPH``; shelter adds owner mortgage-principal outlays (SPM
    outlays concept) when ``include_mortgage_principal`` is set.

    Args:
        ce_df: CE FMLI DataFrame (one row per CU-interview).
        weight_col: Column with the CU's calibrated survey weight.
            Defaults to ``FINLWT21`` (standard FMLI name).
        children_col: Column with the number of persons under 18 in
            the CU. Defaults to ``PERSLT18``.
        include_mortgage_principal: When True (default), add owner
            mortgage-principal outlays to the shelter share.

    Returns:
        Dict mapping each FCSUti component present in ``ce_df`` to a
        share in ``[0, 1]``. Shares sum to 1.0. Components without
        their expenditure columns in the data are omitted.

    Raises:
        ValueError: If ``ce_df`` is missing ``weight_col`` or
            ``children_col``, or if no CUs have children, or if no
            FCSUti component columns are present.
    """
    if weight_col not in ce_df.columns:
        raise ValueError(
            f"CE DataFrame is missing weight column '{weight_col}'"
        )
    if children_col not in ce_df.columns:
        raise ValueError(
            f"CE DataFrame is missing children column '{children_col}'"
        )

    with_children = ce_df[ce_df[children_col] > 0]
    if len(with_children) == 0:
        raise ValueError("No consumer units with children in CE DataFrame")

    weights = with_children[weight_col].astype(float).to_numpy()

    def _weighted_expenditure(pq: str, cq: str) -> Optional[float]:
        if pq not in with_children.columns or cq not in with_children.columns:
            return None
        values = (
            with_children[pq].fillna(0).to_numpy()
            + with_children[cq].fillna(0).to_numpy()
        )
        return float(np.sum(values * weights))

    totals: dict[str, float] = {}
    for component, (pq, cq) in _FMLI_EXPENDITURE_COLUMNS.items():
        if component == "food":
            # Row-wise construction robust to the April 2023 CE food
            # redesign (GROCER-based vintages mixed with legacy FOOD
            # vintages in pooled windows). Lazy import avoids a
            # circular import at module load.
            from .ce_threshold import _food_expenditure

            food_values = _food_expenditure(with_children).to_numpy()
            exp = float(np.sum(food_values * weights))
            if exp > 0:
                totals[component] = exp
            continue
        exp = _weighted_expenditure(pq, cq)
        if exp is None:
            continue
        totals[component] = exp

    # UTIL contains TELEPH; carve telephone out of utilities so the
    # composite weights don't double-count it.
    if "utilities" in totals and "telephone" in totals:
        totals["utilities"] = max(
            totals["utilities"] - totals["telephone"], 0.0
        )

    if include_mortgage_principal and "shelter" in totals:
        for pq, cq in _MORTGAGE_PRINCIPAL_COLUMNS:
            principal = _weighted_expenditure(pq, cq)
            if principal is not None:
                totals["shelter"] += principal

    if not totals:
        raise ValueError(
            "CE DataFrame has no FCSUti expenditure columns "
            f"({list(_FMLI_EXPENDITURE_COLUMNS)})"
        )

    total = sum(totals.values())
    if total <= 0:
        raise ValueError("Total FCSUti expenditure is zero or negative")

    return {component: value / total for component, value in totals.items()}


_STATIC_WEIGHTS_WARNING = (
    "Using static FCSUti weights approximation. For BLS-fidelity "
    "inflation adjustment, derive weights from the CE sample via "
    "compute_fcsuti_weights_from_ce() or supply an explicit "
    "weights= dict keyed by component name."
)


def _resolve_weights(
    weights: Optional[Mapping[str, float]],
) -> dict[str, float]:
    """Normalize a supplied ``weights`` mapping (never warns).

    The fallback-use RuntimeWarning is emitted by the public
    entry-point functions (``get_fcsuti_cpi``,
    ``get_fcsuti_inflation_factor``) so that ``stacklevel=2`` attributes
    the warning to the user regardless of which entry point is called.
    """
    if weights is None:
        return dict(FCSUTI_WEIGHTS)
    if not weights:
        raise ValueError("weights mapping is empty")
    return dict(weights)


@lru_cache(maxsize=8)
def _cached_fcsuti_cpi(
    start_year: int,
    end_year: int,
    base_year: int,
    weights_items: tuple[tuple[str, float], ...],
) -> pd.Series:
    """Immutable-inputs worker for :func:`get_fcsuti_cpi`."""
    weights = dict(weights_items)
    components: dict[str, pd.Series] = {}
    for component in weights:
        series_id = CPI_SERIES.get(component)
        if series_id is None:
            warnings.warn(
                f"No CPI series known for component '{component}'; skipping.",
                RuntimeWarning,
                stacklevel=2,
            )
            continue
        try:
            components[component] = fetch_bls_cpi_series(
                series_id, start_year, end_year
            )
        except Exception as e:
            try:
                components[component] = get_packaged_cpi_series(
                    series_id, start_year, end_year
                )
                warnings.warn(
                    f"BLS API unavailable for {component} ({e}); "
                    "using the packaged CPI store.",
                    RuntimeWarning,
                    stacklevel=2,
                )
            except KeyError:
                warnings.warn(
                    f"Could not fetch {component} CPI ({e}) and it "
                    "is not in the packaged store; dropping it from "
                    "the composite.",
                    RuntimeWarning,
                    stacklevel=2,
                )

    if not components:
        raise ValueError("Could not fetch any CPI component data")

    df = pd.DataFrame(components)
    used_weights = {c: weights[c] for c in df.columns if c in weights}
    if not used_weights:
        raise ValueError(
            "None of the requested FCSUti components returned CPI data"
        )

    # Each CPI series carries its own reference base, so raw levels are
    # not commensurate: summing them weights each component by its
    # level as well as its share (with 2024 levels, shelter's effective
    # weight was 55 percent against a stated 47, telephone's 1.2
    # against 4 — caught by cross-model review 2026-07-18). Rebase
    # every component to the composite's base year before weighting so
    # the stated expenditure shares are the effective ones.
    rebase_year = base_year if base_year in df.index else df.index.min()
    rebasable = [c for c in used_weights if pd.notna(df[c].get(rebase_year))]
    dropped = set(used_weights) - set(rebasable)
    if dropped:
        warnings.warn(
            f"Components missing {rebase_year} values dropped from the "
            f"FCSUti composite: {sorted(dropped)}",
            RuntimeWarning,
            stacklevel=2,
        )
    used_weights = {c: used_weights[c] for c in rebasable}

    denom = sum(used_weights.values())
    if denom <= 0:
        raise ValueError("Requested FCSUti weights sum to zero")
    # Renormalize over the components we actually have so dropped series
    # don't shrink the composite.
    renormalized = {c: w / denom for c, w in used_weights.items()}

    fcsuti = pd.Series(0.0, index=df.index)
    for component, weight in renormalized.items():
        rebased = df[component] / df[component][rebase_year] * 100
        fcsuti += rebased * weight

    if base_year in fcsuti.index:
        fcsuti = fcsuti / fcsuti[base_year] * 100
    fcsuti.name = "FCSUti CPI-U"
    return fcsuti


def get_fcsuti_cpi(
    start_year: int = 2010,
    end_year: int = 2024,
    base_year: int = 2024,
    weights: Optional[Mapping[str, float]] = None,
) -> pd.Series:
    """Compute the FCSUti composite CPI index.

    Args:
        start_year: Inclusive start year for the index.
        end_year: Inclusive end year for the index.
        base_year: Year normalized to 100.
        weights: Optional component-share mapping (e.g. the output of
            :func:`compute_fcsuti_weights_from_ce`). When None, falls
            back to :data:`FCSUTI_WEIGHTS` with a
            :class:`RuntimeWarning` so callers notice when the static
            approximation is in use.

    Returns:
        Annual FCSUti CPI index with base ``base_year`` = 100.
    """
    if weights is None:
        warnings.warn(
            _STATIC_WEIGHTS_WARNING,
            RuntimeWarning,
            stacklevel=2,
        )
    resolved = _resolve_weights(weights)
    return _cached_fcsuti_cpi(
        start_year,
        end_year,
        base_year,
        tuple(sorted(resolved.items())),
    )


def get_fcsuti_inflation_factor(
    from_year: int,
    to_year: int,
    weights: Optional[Mapping[str, float]] = None,
) -> float:
    """Inflation factor between two years via the FCSUti composite.

    Component series come from the BLS API, falling back per series to
    the packaged CPI store (``data/bls/cpi_annual.json``, generated by
    ``scripts/build_cpi_store.py``). If a requested year is outside
    every available series, this raises rather than guessing — the
    previous behavior of substituting a hand-entered factor table or a
    flat 4 percent per year produced silently wrong output.

    Args:
        from_year: Starting year (sets the index base).
        to_year: Target year.
        weights: Optional FCSUti component shares. See
            :func:`get_fcsuti_cpi`.

    Returns:
        Factor to multiply ``from_year`` dollars by to get ``to_year``
        dollars.

    Raises:
        ValueError: If the composite cannot be built for both years.
    """
    if from_year == to_year:
        return 1.0

    if weights is None:
        warnings.warn(
            _STATIC_WEIGHTS_WARNING,
            RuntimeWarning,
            stacklevel=2,
        )
        weights = FCSUTI_WEIGHTS

    try:
        fcsuti = get_fcsuti_cpi(
            start_year=min(from_year, to_year) - 1,
            end_year=max(from_year, to_year) + 1,
            base_year=from_year,
            weights=weights,
        )
    except ValueError as error:
        raise ValueError(
            f"FCSUti composite unavailable for ({from_year}, "
            f"{to_year}): {error}. Regenerate the packaged CPI store "
            "(scripts/build_cpi_store.py) if the requested year has "
            "since been published."
        ) from error
    if to_year not in fcsuti.index or from_year not in fcsuti.index:
        raise ValueError(
            f"FCSUti composite unavailable for ({from_year}, "
            f"{to_year}); available years: {list(fcsuti.index)}. "
            "Regenerate the packaged CPI store "
            "(scripts/build_cpi_store.py) if the requested year has "
            "since been published."
        )
    return fcsuti[to_year] / 100.0
