"""Published SPM threshold series and forecasts for future years.

The packaged series lives in ``spm_calculator/data/bls/threshold_series.json``,
generated by ``scripts/build_threshold_series.py`` from the official BLS
workbook bundled alongside it (SHA-256 recorded in the JSON's provenance
block). Values are never hand-edited here.

Two series ship with the package:

- ``bls-corrected-2026-07-17`` (default): the corrected series BLS
  published on 2026-07-17 after finding errors in the code that produced
  the 2019-2024 thresholds. Full precision, 2005-2024, including
  standard errors and tenure population shares. Workbook footnote 1:
  these are the thresholds Census uses to produce SPM poverty
  statistics. The revised-methodology segment (2019+) is anchored at
  82% of the median FCSUti range (83% before the correction).
- ``package-legacy-0.3``: the values shipped in spm-calculator <= 0.3.1,
  retained verbatim so results produced with earlier releases stay
  reproducible. Note: its 2022-2023 values match no BLS or Census
  publication (see docs/bls-2026-correction.md).

The BLS publishes thresholds with a lag, so forecasting is necessary
for current and future year calculations: years past the latest
published year compound CPI projections off the latest published base.
"""

import json
import warnings
from functools import lru_cache
from importlib import resources
from typing import Optional

DEFAULT_SERIES = "bls-corrected-2026-07-17"

#: Series name for the values shipped in spm-calculator <= 0.3.1.
LEGACY_SERIES = "package-legacy-0.3"


@lru_cache(maxsize=1)
def _threshold_data() -> dict:
    """Load the packaged threshold-series document."""
    ref = resources.files("spm_calculator").joinpath(
        "data/bls/threshold_series.json"
    )
    return json.loads(ref.read_text())


def _flatten_series(name: str) -> dict[int, dict[str, float]]:
    """Flatten a series entry to ``{year: {tenure: threshold}}``.

    For the corrected BLS series, the canonical view splices the
    old-methodology segment (2005-2018) with the revised-methodology
    segment (2019-2024, using the workbook's "2019 Revised" column) —
    the same splice Census uses for its published SPM statistics.
    """
    doc = _threshold_data()
    try:
        entry = doc["series"][name]
    except KeyError:
        raise ValueError(
            f"Unknown threshold series {name!r}. "
            f"Available: {sorted(doc['series'])}"
        ) from None

    flat: dict[int, dict[str, float]] = {}
    if "segments" in entry:
        # Later segments win overlapping years (2019: revised over
        # published), matching the operative Census series.
        for segment in entry["segments"].values():
            for year_str, tenures in segment["years"].items():
                flat[int(year_str)] = {
                    tenure: measures["threshold"]
                    for tenure, measures in tenures.items()
                }
    else:
        for year_str, tenures in entry["years"].items():
            flat[int(year_str)] = {
                tenure: measures["threshold"]
                for tenure, measures in tenures.items()
            }
    return flat


def _measure_by_year(name: str, measure: str) -> dict[int, dict[str, float]]:
    doc = _threshold_data()
    entry = doc["series"][name]
    out: dict[int, dict[str, float]] = {}
    segments = (
        entry["segments"].values()
        if "segments" in entry
        else [{"years": entry["years"]}]
    )
    for segment in segments:
        for year_str, tenures in segment["years"].items():
            values = {
                tenure: measures[measure]
                for tenure, measures in tenures.items()
                if measure in measures
            }
            if values:
                out[int(year_str)] = values
    return out


#: Full-precision published thresholds by year and tenure for the
#: default (corrected) series. Kept as a module-level dict because
#: policyengine-us and earlier callers index it directly.
HISTORICAL_THRESHOLDS: dict[int, dict[str, float]] = _flatten_series(
    DEFAULT_SERIES
)

# Latest year with published BLS thresholds — derived from the data, not
# maintained by hand.
LATEST_PUBLISHED_YEAR = max(HISTORICAL_THRESHOLDS)

# CPI-U annual inflation projections (from CBO/Federal Reserve forecasts)
# These should be updated periodically based on latest forecasts
CPI_PROJECTIONS = {
    2025: 0.025,  # 2.5% projected inflation
    2026: 0.023,  # 2.3%
    2027: 0.022,  # 2.2%
    2028: 0.020,  # 2.0% (long-run target)
    2029: 0.020,
    2030: 0.020,
}

# Default long-run inflation assumption
DEFAULT_INFLATION = 0.020  # 2.0% Fed target

# Forecasts compound inflation off the latest published year. Past this
# horizon the cumulative drift from the published base is large enough
# that callers should know they are past the region where the forecast
# is even approximately reliable — we emit a RuntimeWarning.
FORECAST_WARNING_HORIZON = 5


def _resolve_series(series: Optional[str]) -> dict[int, dict[str, float]]:
    if series is None or series == DEFAULT_SERIES:
        return HISTORICAL_THRESHOLDS
    return _flatten_series(series)


def get_available_series() -> list[str]:
    """List the threshold series bundled with the package."""
    return sorted(_threshold_data()["series"])


def get_series_provenance(series: Optional[str] = None) -> dict:
    """Return the provenance block for a bundled series."""
    doc = _threshold_data()
    name = series or DEFAULT_SERIES
    try:
        return dict(doc["series"][name].get("provenance", {}))
    except KeyError:
        raise ValueError(
            f"Unknown threshold series {name!r}. "
            f"Available: {sorted(doc['series'])}"
        ) from None


def get_standard_errors(
    year: int, series: Optional[str] = None
) -> dict[str, float]:
    """Published standard errors of the thresholds, where available."""
    by_year = _measure_by_year(series or DEFAULT_SERIES, "standard_error")
    if year not in by_year:
        raise ValueError(
            f"Standard errors not available for {year}. "
            f"Available years: {sorted(by_year)}"
        )
    return by_year[year].copy()


def get_tenure_shares(
    year: int, series: Optional[str] = None
) -> dict[str, float]:
    """Published tenure population shares of the estimation sample.

    Useful for collapsing the three tenure thresholds to a single
    weighted-average threshold.
    """
    by_year = _measure_by_year(series or DEFAULT_SERIES, "tenure_share")
    if year not in by_year:
        raise ValueError(
            f"Tenure shares not available for {year}. "
            f"Available years: {sorted(by_year)}"
        )
    return by_year[year].copy()


def get_inflation_rate(year: int) -> float:
    """
    Get projected or assumed inflation rate for a year.

    Args:
        year: Calendar year

    Returns:
        Annual inflation rate (e.g., 0.025 for 2.5%)
    """
    return CPI_PROJECTIONS.get(year, DEFAULT_INFLATION)


def calculate_cumulative_inflation(from_year: int, to_year: int) -> float:
    """
    Calculate cumulative inflation factor between two years.

    Args:
        from_year: Starting year
        to_year: Ending year

    Returns:
        Cumulative inflation factor (e.g., 1.05 for 5% total inflation)
    """
    if to_year <= from_year:
        return 1.0

    factor = 1.0
    for year in range(from_year + 1, to_year + 1):
        factor *= 1 + get_inflation_rate(year)

    return factor


def forecast_thresholds(
    year: int,
    base_year: Optional[int] = None,
    custom_inflation: Optional[float] = None,
    series: Optional[str] = None,
) -> dict[str, float]:
    """
    Forecast SPM thresholds for a future year.

    Uses historical thresholds and CPI projections to estimate thresholds
    for years not yet published by BLS.

    Args:
        year: Target year for forecast
        base_year: Year to use as base for projection. If None, uses
                   the latest published year.
        custom_inflation: Optional custom annual inflation rate to use
                         instead of projections.
        series: Bundled threshold series to project from. Defaults to
                the corrected BLS series.

    Returns:
        Dict with forecasted threshold values by tenure type. Values
        retain sub-dollar precision; the previous implementation cast
        to ``int`` before composition with equivalence and geographic
        adjustments, introducing ~$1 drift vs. the mathematically exact
        product.
    """
    thresholds = _resolve_series(series)
    latest = max(thresholds)
    available = sorted(thresholds)
    if year <= latest:
        if year in thresholds:
            return thresholds[year].copy()
        raise ValueError(
            f"Year {year} is below the earliest supported year "
            f"({available[0]}). Historical SPM thresholds are only "
            f"available for {available[0]}–{latest}."
        )

    # Use latest published year as base
    if base_year is None:
        base_year = latest

    _maybe_warn_far_forecast(year, base_year)

    base_thresholds = thresholds[base_year]

    # Calculate inflation adjustment
    if custom_inflation is not None:
        years_ahead = year - base_year
        inflation_factor = (1 + custom_inflation) ** years_ahead
    else:
        inflation_factor = calculate_cumulative_inflation(base_year, year)

    # Keep float precision through the forecast multiply. Downstream
    # code composes this with `equiv_scale * geoadj`, so rounding to
    # int early introduces up to ~$1 drift vs. the exact product.
    forecasted = {
        tenure: float(value * inflation_factor)
        for tenure, value in base_thresholds.items()
    }

    return forecasted


def _maybe_warn_far_forecast(year: int, base_year: int) -> None:
    """Emit a RuntimeWarning once the forecast horizon exceeds N years.

    Silently compounding decades of 2% inflation off a published base
    is not useful output; the warning gives downstream code a
    chance to surface the uncertainty to users. `get_threshold_with_metadata`
    also exposes this horizon via the returned dict.
    """
    horizon = year - base_year
    if horizon > FORECAST_WARNING_HORIZON:
        warnings.warn(
            f"Forecasting SPM thresholds {horizon} years past the latest "
            f"published year ({base_year}); values compound default "
            f"inflation beyond the published CPI projection window "
            f"({max(CPI_PROJECTIONS)}). Treat results as illustrative.",
            RuntimeWarning,
            stacklevel=3,
        )


def get_thresholds(
    year: int,
    allow_forecast: bool = True,
    custom_inflation: Optional[float] = None,
    series: Optional[str] = None,
) -> dict[str, float]:
    """
    Get SPM thresholds for any year, with optional forecasting.

    This is the main entry point for getting thresholds. It returns
    published values when available and forecasts when necessary.

    Args:
        year: Target year
        allow_forecast: If True, forecast future years. If False,
                       raise error for unpublished years.
        custom_inflation: Optional custom inflation rate for forecasting.
        series: Bundled threshold series to read. Defaults to the
                corrected BLS series; ``"package-legacy-0.3"``
                reproduces spm-calculator <= 0.3.1 results.

    Returns:
        Dict with threshold values by tenure type

    Raises:
        ValueError: If year not available and forecasting disabled
    """
    thresholds = _resolve_series(series)
    if year in thresholds:
        return thresholds[year].copy()

    if not allow_forecast:
        raise ValueError(
            f"Thresholds not available for {year} and forecasting disabled. "
            f"Latest published: {max(thresholds)}"
        )

    return forecast_thresholds(
        year, custom_inflation=custom_inflation, series=series
    )


def get_threshold_with_metadata(
    year: int,
    allow_forecast: bool = True,
    custom_inflation: Optional[float] = None,
    series: Optional[str] = None,
) -> dict:
    """
    Get thresholds with metadata about source and methodology.

    Args:
        year: Target year
        allow_forecast: If True, forecast future years.
        custom_inflation: Optional custom inflation rate.
        series: Bundled threshold series to read.

    Returns:
        Dict with:
        - thresholds: threshold values by tenure
        - year: the year
        - series: name of the bundled series used
        - provenance: the series' provenance block
        - source: 'published' or 'forecast'
        - base_year: base year used for forecast (if applicable)
        - inflation_factor: total inflation applied (if forecasted)
    """
    series_name = series or DEFAULT_SERIES
    resolved = _resolve_series(series)
    latest = max(resolved)
    is_forecast = year > latest

    if is_forecast and not allow_forecast:
        raise ValueError(f"Year {year} requires forecasting")

    thresholds = get_thresholds(
        year,
        allow_forecast=allow_forecast,
        custom_inflation=custom_inflation,
        series=series,
    )

    result = {
        "thresholds": thresholds,
        "year": year,
        "series": series_name,
        "provenance": get_series_provenance(series_name),
        "source": "forecast" if is_forecast else "published",
    }

    if is_forecast:
        base_year = latest
        if custom_inflation is not None:
            years_ahead = year - base_year
            inflation_factor = (1 + custom_inflation) ** years_ahead
        else:
            inflation_factor = calculate_cumulative_inflation(base_year, year)

        result["base_year"] = base_year
        result["inflation_factor"] = inflation_factor
        result["inflation_rate"] = (
            custom_inflation if custom_inflation else get_inflation_rate(year)
        )
        # Tell callers whether we're past the point where the
        # forecast is even approximately reliable. Matches the
        # RuntimeWarning emitted by `forecast_thresholds`.
        result["horizon_years"] = year - base_year
        result["beyond_reliable_horizon"] = (
            year - base_year
        ) > FORECAST_WARNING_HORIZON

    return result


def get_available_years(series: Optional[str] = None) -> list[int]:
    """Get list of years with published thresholds."""
    return sorted(_resolve_series(series).keys())


def get_latest_published_year(series: Optional[str] = None) -> int:
    """Get the most recent year with published BLS thresholds."""
    return max(_resolve_series(series))
