"""Tests for the bundled threshold series and their provenance.

The packaged data (``spm_calculator/data/bls/threshold_series.json``)
is generated by ``scripts/build_threshold_series.py`` from the official
BLS workbook bundled next to it — these tests pin the wiring, the
provenance, and a handful of externally-verifiable values from the
Census P60 reports and the corrected BLS workbook.
"""

import hashlib
import json
from importlib import resources

import pytest

from scripts.build_threshold_series import build_document
from spm_calculator.published_thresholds import (
    DEFAULT_SERIES,
    HISTORICAL_THRESHOLDS,
    LATEST_PUBLISHED_YEAR,
    LEGACY_SERIES,
    get_available_series,
    get_available_years,
    get_latest_published_year,
    get_published_thresholds,
    get_series_provenance,
    get_standard_errors,
    get_tenure_shares,
    get_threshold_with_metadata,
)

TRUSTED_CORRECTED_WORKBOOK_SHA256 = (
    "e7931a1f2540d52877d6fd14a8ed1e421e977a85c952ae1b6f690a04d904f2cb"
)
TRUSTED_CURRENT_WORKBOOK_SHA256 = (
    "95f39fb5479ee5c196de627e06e10efd59af5148cf1c8466924e3fb2e5e2bd3b"
)


class TestSeriesRegistry:
    def test_three_series_bundled(self):
        assert get_available_series() == [
            "bls-corrected-2026-07-17",
            "census-published-pre-correction",
            "package-legacy-0.3",
        ]
        assert DEFAULT_SERIES == "bls-corrected-2026-07-17"
        assert LEGACY_SERIES == "package-legacy-0.3"

    def test_unknown_series_raises(self):
        with pytest.raises(ValueError, match="Unknown threshold series"):
            get_published_thresholds(2024, series="nope")


class TestSourceOnlyAccess:
    @pytest.mark.parametrize(
        "accessor",
        [
            get_published_thresholds,
            get_threshold_with_metadata,
        ],
    )
    @pytest.mark.parametrize("year", [1999, 2004, 2026, 2035, 2100])
    def test_unavailable_years_raise_without_forecasting(self, accessor, year):
        with pytest.raises(ValueError, match="not available"):
            accessor(year)

    @pytest.mark.parametrize(
        "series",
        [
            "census-published-pre-correction",
            LEGACY_SERIES,
        ],
    )
    def test_archival_series_do_not_fall_back_to_corrected_data(self, series):
        assert get_latest_published_year(series) == 2024
        assert 2025 not in get_available_years(series)
        with pytest.raises(ValueError, match="not available"):
            get_published_thresholds(2025, series=series)
        with pytest.raises(ValueError, match="not available"):
            get_threshold_with_metadata(2025, series=series)

    def test_returned_thresholds_cannot_change_the_source(self):
        values = get_published_thresholds(2025)
        values["renter"] = 0
        assert get_published_thresholds(2025)["renter"] == 41700.555713
        assert HISTORICAL_THRESHOLDS[2025]["renter"] == 41700.555713

    def test_metadata_is_an_independent_source_snapshot(self):
        metadata = get_threshold_with_metadata(2025)
        metadata["thresholds"]["renter"] = 0
        metadata["provenance"]["sha256"] = "changed"
        metadata["segment_provenance"]["bls_stated_growth_percent"][
            "renter"
        ] = 0
        fresh = get_threshold_with_metadata(2025)
        assert fresh["thresholds"]["renter"] == 41700.555713
        assert (
            fresh["provenance"]["sha256"] == TRUSTED_CORRECTED_WORKBOOK_SHA256
        )
        assert (
            fresh["segment_provenance"]["bls_stated_growth_percent"]["renter"]
            == 6.325
        )


class TestCorrectedSeries:
    def test_default_series_is_corrected(self):
        assert get_published_thresholds(2024) == get_published_thresholds(
            2024, series=DEFAULT_SERIES
        )

    def test_workbook_sha256_matches_trusted_literal(self):
        """Neither the workbook nor its JSON stamp can redefine trust."""
        provenance = get_series_provenance()
        workbook = resources.files("spm_calculator").joinpath(
            "data/bls/spm_threshold_200524_corrected.xlsx"
        )
        digest = hashlib.sha256(workbook.read_bytes()).hexdigest()
        assert digest == TRUSTED_CORRECTED_WORKBOOK_SHA256
        assert provenance["sha256"] == TRUSTED_CORRECTED_WORKBOOK_SHA256

        current_workbook = resources.files("spm_calculator").joinpath(
            "data/bls/spm_thresholds.xlsx"
        )
        current_digest = hashlib.sha256(
            current_workbook.read_bytes()
        ).hexdigest()
        assert current_digest == TRUSTED_CURRENT_WORKBOOK_SHA256

    def test_2019_uses_revised_column(self):
        """The canonical splice takes the workbook's "2019 Revised"
        column for 2019, matching the operative Census series."""
        thresholds = get_published_thresholds(2019)
        assert thresholds["owner_with_mortgage"] == pytest.approx(29076.17484)
        assert thresholds["renter"] == pytest.approx(28913.050035)

    def test_full_precision_survives_round_trip(self):
        """BLS warns that all significant digits matter; the packaged
        values must not be rounded to whole dollars."""
        renter = get_published_thresholds(2024)["renter"]
        assert renter != round(renter)

    def test_standard_errors_and_shares(self):
        se = get_standard_errors(2024)
        shares = get_tenure_shares(2024)
        assert se["renter"] == pytest.approx(325.113614)
        assert sum(shares.values()) == pytest.approx(1.0, abs=1e-6)

    def test_2025_continues_corrected_series_at_full_precision(self):
        values = get_published_thresholds(2025)
        assert values == pytest.approx(
            {
                "owner_with_mortgage": 41322.707394,
                "owner_without_mortgage": 34325.99772,
                "renter": 41700.555713,
            }
        )
        assert {tenure: round(value) for tenure, value in values.items()} == {
            "owner_with_mortgage": 41323,
            "owner_without_mortgage": 34326,
            "renter": 41701,
        }

    def test_metadata_identifies_published_2025_segment(self):
        metadata = get_threshold_with_metadata(2025)
        assert metadata["source"] == "published"
        assert metadata["series"] == DEFAULT_SERIES
        assert metadata["segment"] == "bls-published-2025"
        assert metadata["segment_provenance"]["retrieved"] == "2026-09-04"

    def test_2025_segment_records_page_provenance_and_growth(self):
        ref = resources.files("spm_calculator").joinpath(
            "data/bls/threshold_series.json"
        )
        segment = json.loads(ref.read_text())["series"][DEFAULT_SERIES][
            "segments"
        ]["bls-published-2025"]
        provenance = segment["provenance"]
        assert provenance["retrieved"] == "2026-09-04"
        assert provenance["page_source_url"].endswith(
            "spm_thresholds_2025.htm"
        )
        assert provenance["bls_stated_growth_percent"] == {
            "owner_with_mortgage": 5.332,
            "owner_without_mortgage": 4.402,
            "renter": 6.325,
        }
        assert "full-precision" in provenance["precision"]

    def test_2025_standard_errors_and_shares_are_published(self):
        assert get_standard_errors(2025) == pytest.approx(
            {
                "owner_with_mortgage": 327.35414802,
                "owner_without_mortgage": 560.28664871,
                "renter": 393.03526083,
            }
        )
        assert sum(get_tenure_shares(2025).values()) == pytest.approx(1.0)

    def test_covers_2005_through_2025(self):
        years = get_available_years()
        assert years[0] == 2005
        assert years[-1] == 2025
        assert len(years) == 21
        assert get_latest_published_year() == LATEST_PUBLISHED_YEAR == 2025


class TestPublishedPreCorrectionSeries:
    """Values Census actually published for 2019-2024, cross-verified
    against two consecutive P60 reports each."""

    @pytest.mark.parametrize(
        "year,expected",
        [
            (2019, (29080, 24413, 29194)),
            (2020, (29959, 25222, 30150)),
            (2021, (31107, 26279, 31453)),
            (2022, (34235, 28909, 34518)),
            (2023, (36915, 30870, 37482)),
            (2024, (39068, 32586, 39430)),
        ],
    )
    def test_matches_p60_reports(self, year, expected):
        mtg, no_mtg, renter = expected
        thresholds = get_published_thresholds(
            year, series="census-published-pre-correction"
        )
        assert thresholds["owner_with_mortgage"] == mtg
        assert thresholds["owner_without_mortgage"] == no_mtg
        assert thresholds["renter"] == renter

    def test_correction_is_small(self):
        """The 2026-07-17 correction moved every published threshold by
        less than 2% — the sanity bound that distinguishes BLS's code
        error from this package's earlier hand-entry errors (up to 8%)."""
        for year in range(2019, 2025):
            published = get_published_thresholds(
                year, series="census-published-pre-correction"
            )
            corrected = get_published_thresholds(year)
            for tenure, value in published.items():
                assert abs(corrected[tenure] / value - 1) < 0.02, (
                    year,
                    tenure,
                )


class TestLegacySeries:
    def test_legacy_values_preserved_verbatim(self):
        """Results produced with spm-calculator <= 0.3.1 stay
        reproducible through the legacy series."""
        thresholds = get_published_thresholds(2024, series=LEGACY_SERIES)
        assert thresholds["renter"] == 39430
        assert (
            get_published_thresholds(2020, series=LEGACY_SERIES)["renter"]
            == 28881
        )

    def test_legacy_2022_2023_documented_as_unsourced(self):
        """The legacy 2022-2023 values match no BLS/Census publication;
        the provenance note must say so."""
        note = get_series_provenance(LEGACY_SERIES)["note"]
        assert "match" in note and "no BLS or Census publication" in note

    def test_json_is_regenerable(self):
        """Regeneration must deep-match every threshold, SE, and share."""
        ref = resources.files("spm_calculator").joinpath(
            "data/bls/threshold_series.json"
        )
        packaged = json.loads(ref.read_text())
        regenerated = build_document()
        assert packaged["generated_by"] == "scripts/build_threshold_series.py"
        assert regenerated == packaged
