"""Tests for the bundled threshold series and their provenance.

The packaged data (``spm_calculator/data/bls/threshold_series.json``)
is generated by ``scripts/build_threshold_series.py`` from the official
BLS workbook bundled next to it — these tests pin the wiring, the
provenance, and a handful of externally-verifiable values from the
Census P60 reports and the corrected BLS workbook.
"""

import hashlib
import json
from importlib import resources

import pytest

from spm_calculator.forecast import (
    DEFAULT_SERIES,
    LEGACY_SERIES,
    get_available_series,
    get_available_years,
    get_series_provenance,
    get_standard_errors,
    get_tenure_shares,
    get_thresholds,
)


class TestSeriesRegistry:
    def test_three_series_bundled(self):
        assert get_available_series() == [
            "bls-corrected-2026-07-17",
            "census-published-pre-correction",
            "package-legacy-0.3",
        ]
        assert DEFAULT_SERIES == "bls-corrected-2026-07-17"
        assert LEGACY_SERIES == "package-legacy-0.3"

    def test_unknown_series_raises(self):
        with pytest.raises(ValueError, match="Unknown threshold series"):
            get_thresholds(2024, series="nope")


class TestCorrectedSeries:
    def test_default_series_is_corrected(self):
        assert get_thresholds(2024) == get_thresholds(
            2024, series=DEFAULT_SERIES
        )

    def test_workbook_sha256_matches_bundled_file(self):
        """The provenance SHA-256 must match the actual bundled
        workbook — the JSON cannot silently drift from its source."""
        provenance = get_series_provenance()
        workbook = resources.files("spm_calculator").joinpath(
            "data/bls/spm_threshold_200524_corrected.xlsx"
        )
        digest = hashlib.sha256(workbook.read_bytes()).hexdigest()
        assert provenance["sha256"] == digest

    def test_2019_uses_revised_column(self):
        """The canonical splice takes the workbook's "2019 Revised"
        column for 2019, matching the operative Census series."""
        thresholds = get_thresholds(2019)
        assert thresholds["owner_with_mortgage"] == pytest.approx(29076.17484)
        assert thresholds["renter"] == pytest.approx(28913.050035)

    def test_full_precision_survives_round_trip(self):
        """BLS warns that all significant digits matter; the packaged
        values must not be rounded to whole dollars."""
        renter = get_thresholds(2024)["renter"]
        assert renter != round(renter)

    def test_standard_errors_and_shares(self):
        se = get_standard_errors(2024)
        shares = get_tenure_shares(2024)
        assert se["renter"] == pytest.approx(325.113614)
        assert sum(shares.values()) == pytest.approx(1.0, abs=1e-6)

    def test_covers_2005_through_2024(self):
        years = get_available_years()
        assert years[0] == 2005
        assert years[-1] == 2024
        assert len(years) == 20


class TestPublishedPreCorrectionSeries:
    """Values Census actually published for 2019-2024, cross-verified
    against two consecutive P60 reports each."""

    @pytest.mark.parametrize(
        "year,expected",
        [
            (2019, (29080, 24413, 29194)),
            (2020, (29959, 25222, 30150)),
            (2021, (31107, 26279, 31453)),
            (2022, (34235, 28909, 34518)),
            (2023, (36915, 30870, 37482)),
            (2024, (39068, 32586, 39430)),
        ],
    )
    def test_matches_p60_reports(self, year, expected):
        mtg, no_mtg, renter = expected
        thresholds = get_thresholds(
            year, series="census-published-pre-correction"
        )
        assert thresholds["owner_with_mortgage"] == mtg
        assert thresholds["owner_without_mortgage"] == no_mtg
        assert thresholds["renter"] == renter

    def test_correction_is_small(self):
        """The 2026-07-17 correction moved every published threshold by
        less than 2% — the sanity bound that distinguishes BLS's code
        error from this package's earlier hand-entry errors (up to 8%)."""
        for year in range(2019, 2025):
            published = get_thresholds(
                year, series="census-published-pre-correction"
            )
            corrected = get_thresholds(year)
            for tenure, value in published.items():
                assert abs(corrected[tenure] / value - 1) < 0.02, (
                    year,
                    tenure,
                )


class TestLegacySeries:
    def test_legacy_values_preserved_verbatim(self):
        """Results produced with spm-calculator <= 0.3.1 stay
        reproducible through the legacy series."""
        thresholds = get_thresholds(2024, series=LEGACY_SERIES)
        assert thresholds["renter"] == 39430
        assert get_thresholds(2020, series=LEGACY_SERIES)["renter"] == 28881

    def test_legacy_2022_2023_documented_as_unsourced(self):
        """The legacy 2022-2023 values match no BLS/Census publication;
        the provenance note must say so."""
        note = get_series_provenance(LEGACY_SERIES)["note"]
        assert "match" in note and "no BLS or Census publication" in note

    def test_json_is_regenerable(self):
        """The packaged JSON must declare its generator so the next
        revision is a regeneration, not archaeology."""
        ref = resources.files("spm_calculator").joinpath(
            "data/bls/threshold_series.json"
        )
        doc = json.loads(ref.read_text())
        assert doc["generated_by"] == "scripts/build_threshold_series.py"
